gemfile:
  - gemfiles/as_5.0.gemfile
  - gemfiles/as_5.1.gemfile
  - gemfiles/as_5.2.gemfile
  - gemfiles/as_6.0.gemfile
language: ruby
matrix:
  fast_finish: true
  exclude:
    - gemfile: gemfiles/as_6.0.gemfile
      rvm: 2.4
rvm:
  - 2.4
  - 2.5
  - 2.6
sudo: false
